version: "3.8"

services:
  frontend:
    container_name: lp-toolkit-frontend
    build:
      context: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
    restart: unless-stopped
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    container_name: lp-toolkit-backend
    build:
      context: backend
    ports:
      - 5050:5050
    volumes:
      - ./backend:/usr/src/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/lp-toolkit
    restart: unless-stopped
    networks:
      - express-mongo
      - react-express
    depends_on:
      - mongo

  langchain:
    container_name: lp-toolkit-langchain
    build: ./langchain
    ports:
      - 8000:8000
    volumes:
      - ./langchain/app:/usr/src/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
    restart: unless-stopped
    networks:
      - express-mongo
      - react-express
    depends_on:
      - mongo

  proxy:
    image: nginx
    container_name: lp-toolkit-proxy
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
    volumes:
      - ./proxy/nginx.proxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      - react-express

  mongo:
    container_name: lp-toolkit-mongo
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    restart: unless-stopped
    networks:
      - express-mongo

networks:
  react-express:
  express-mongo:
