version: '3.8'

services:
  frontend:
    container_name: lp-toolkit-frontend
    build:
      context: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    restart: unless-stopped
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    container_name: lp-toolkit-backend
    build:
      context: backend
    ports:
      - "5050:5050"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/lp-toolkit
    restart: unless-stopped
    networks:
      - express-mongo
      - react-express
    depends_on:
      - mongo

  fastapi:
    container_name: lp-toolkit-fastapi
    build: ./lp-toolkit
    ports:
      - "8000:8000"
    volumes:
      - ./lp-toolkit/app:/usr/src/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    networks:
      - express-mongo  # Include if FastAPI needs to communicate with MongoDB
      - react-express  # For communication with the frontend

  mongo:
    container_name: lp-toolkit-mongo
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    restart: unless-stopped
    networks:
      - express-mongo
    expose:
      - "27017"

networks:
  react-express:
  express-mongo:
