name: Backend CI/CD

on:
  push:
    branches: ["**"]
    paths:
      - "backend/**"
  pull_request:
    branches: ["**"]
    paths:
      - "backend/**"
  workflow_dispatch:

# Jobs to run
jobs:
  CI:
    # This job runs on Linux
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks to run as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies

        run: |
          cd backend
          npm ci

      #Add Tests Here

      - name: Build
        run: |
          cd backend   
          npm run build
        env:
          CI: false

