name: FastAPI CI/CD

on:
  push:
    branches: ["**"]
    paths:
      - "lp-toolkit/**"
  pull_request:
    branches: [main]
    paths:
      - "lp-toolkit/**"

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Python Virtual ENV
        run: pip3 install virtualenv

      - name: Cache Virtual ENV
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('lp-toolkit/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Activate Virtual ENV and Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r lp-toolkit/requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest lp-toolkit/tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
