name: Frontend CI/CD

on:
  push:
    branches: ["**"]
    paths:
      - "frontend/**"
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: |
          cd frontend
          npm ci

      #Add tests here

      - name: Build
        run: |
          cd frontend  
          npm run build
        env:
          CI: false
